kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apple-ingress
  annotations:
    ingress.kubernetes.io/ssl-proxy-headers: 'X-Forwarded-Proto:https'
    ingress.kubernetes.io/ssl-redirect: 'true'
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: apple.gw.firstdag.com
  - http:
      paths:
        - path: /
          backend:
            serviceName: apple-service
            servicePort: 8000